### ISSUE TITLE
Subgrouping by scope

### ISSUE THREAD

**Issue by karol-f** [stevemao/conventional-changelog-angular#1]
In older version of conventional-changelog (0.0.17), changelog was automatically grouped not only by "Bug Fixes"/"Features" but also subgrouped by "scope". Like in example below:

![grouping](https://www.dropbox.com/s/qb7vc7kny161nau/changelog_grouping.png?dl=1)

As we can see "cart" scope become group for all commits from that scope. Is this possible to have same functionality in current version of angular preset? If no, how to achieve it?

**Comment by stevemao** [comment]
https://github.com/ajoslin/conventional-changelog/issues/140

**Comment by stevemao** [comment]
@bcoe @nexdrew @kazupon @Tapppi I'm reopening this incase you guys think this is a good idea?

**Comment by krik** [comment]
@stevemao Referring to your statement in the linked issue, that you can't remember that subgrouping existed. You can see it if you scroll down the changelogs linked in the example section, e.g. Karma https://github.com/karma-runner/karma/blob/master/CHANGELOG.md#0130-2015-07-15

Gonna subscribe the issues in case I find time to work on this.

**Comment by Tapppi** [comment]
Since this got some attention in `standard-version`, I think this is a good idea.

**Comment by bcoe** [comment]
@Tapppi @stevemao it seems like a reasonable feature to me, if yo've added a prefix we might as well group by it?

**Comment by hutson** [comment]
We're closing this issue out as this repository has been merged into our [`conventional-changelog`](https://github.com/conventional-changelog/conventional-changelog) mono-repository.

If you would like to see this change incorporated into `conventional-changelog` please consider re-opening the issue against the `conventional-changelog` mono-repository.
