### ISSUE TITLE
Returning gitRawCommitsOpts

### ISSUE THREAD

**Issue by tlimpanont** [stevemao/conventional-changelog-angular#15]
I would like to overwrite the gitRawCommitsOpts. 

``` javascript
conventionalChangelog(
      {
        preset: 'angular', releaseCount: 0,  gitRawCommitsOpts: {
          merges: true,
          noMerges: false
        }
      })
```

But it seems like that when using angular mode `gitRawCommitsOpts` is not used in the source code?

Please check:
https://github.com/conventional-changelog/conventional-changelog-angular/blob/master/index.js#L117

**Comment by tlimpanont** [comment]
Ok, i've got it:

``` javascript
  conventionalChangelog(
        {
          preset: 'angular', releaseCount: 0
        }, {}, {
          noMerges: undefined,
          merges: undefined
        })
```

**Comment by stevemao** [comment]
I strongly suggest you to use `standard version` instead of hacking around.
