### ISSUE TITLE
Alternate version proposal

### ISSUE THREAD

**Issue by topheman** [stevemao/conventional-changelog-angular#2]
Hie @stevemao 

Congratulations for the work you've done on this project. I have a question:

I follow the angular commit convention on my projects, but ... launching your changelog generator, I realized that I missed the column ... 
- mine: feat(scope) subject
- should be: feat(scope)`:` subject

Yeah, you can laugh :D ... All my commits are like that ... 

So `conventional-changelog-angular` doesn't work out of the box. It simply needs a little adjustement [here](https://github.com/stevemao/conventional-changelog-angular/blob/master/index.js#L8) where the regexp :
- instead of `/^(\w*)(?:\((.*)\))?\: (.*)$/`
- would be `/^(\w*)(?:\((.*)\))?\:? (.*)$/`

It should be totally backwards compatible with the actual version but if I were you, as a maintainer, I wouldn't accept that kind of pull request because it's too much user specific, so I think the right way is that I make my own preset, based on yours.

Are you ok with that ? Just say yes, I'll manage everything myself ;D

Tophe

**Comment by stevemao** [comment]
You could do (not tested just an idea)

``` js
var config = require('conventional-changelog-angular')
    .then(function(data) {
        ...
        return modifiedData;
    })
```

**Comment by stevemao** [comment]
Or just change that regex option in `conventional-changelog`

**Comment by topheman** [comment]
@stevemao this first option deserves to be tested, it's a good idea. At least, the new config would still rely on the original module for evolutions and fixes (easier to maintain than merges).

Thanks, I'll try that in the week-end.

**Comment by stevemao** [comment]
The second option achieves the save result. Reopen if you have any issue. Thanks.

**Comment by topheman** [comment]
Thank you for the advice @stevemao it's implemented: https://github.com/topheman/conventional-changelog-angular-loose

The unit tests run in both angular "strict" & "loose" mode and are green.

It's available on npm: https://www.npmjs.com/package/conventional-changelog-angular-loose

I'll bump to v1.0.0 once I'll have used it a little. If you have any comments, just drop them on the repo.

**Comment by stevemao** [comment]
@topheman I'd call it config instead of preset. Because `conventional-changelog` doesn't have it out of the box. also the code could be simplified as

``` js
modules.exports = require('conventional-changelog-angular')
  .then(function(data) {
    data.parserOpts.headerPattern = /^(\w*)(?:\((.*)\))?\:? (.*)$/;
    return data;
  });
```

**Comment by topheman** [comment]
@stevemao I've taken in account your feedback, they are available on this [branch](https://github.com/topheman/conventional-changelog-angular-loose/tree/feature/feedbacks), you can see the diff [here](https://github.com/topheman/conventional-changelog-angular-loose/commit/f7635c477817653168bd7147cad98afd7d192482)
