### ISSUE TITLE
Document Commit Subject Type Check

### ISSUE THREAD

**Issue by ghost** [stevemao/conventional-changelog-angular#4]
I'm in the process of extending `conventional-changelog-angular` in the form of a fork, but couldn't figure out why `typeof commit.subject === 'string'` was necessary.

If it's needed could a unit test be added to help get the project up to 100% test coverage.

**Comment by stevemao** [comment]
same as #6, PR welcome :)

**Comment by hutson** [comment]
We're closing this issue out as this repository has been merged into our [`conventional-changelog`](https://github.com/conventional-changelog/conventional-changelog) mono-repository.

If you would like to see this change incorporated into `conventional-changelog` please consider re-opening the issue against the `conventional-changelog` mono-repository.
