### ISSUE TITLE
Test Commit Type Else

### ISSUE THREAD

**Issue by ghost** [stevemao/conventional-changelog-angular#5]
The long chain of commit type conditionals doesn't have a test for the `else` case where no type matches. 

In my fork of `conventional-changelog-angular` I added `gitDummyCommit(['what(ngOptions): unknown type', 'BREAKING CHANGE: The Change is huge.']);` to the _BREAKING CHANGE_ test case, along with `expect(chunk).to.include('what');` as an assertion.

That resolve that missing test case.

**Comment by stevemao** [comment]
PR welcome :)

**Comment by hutson** [comment]
We're closing this issue out as this repository has been merged into our [`conventional-changelog`](https://github.com/conventional-changelog/conventional-changelog) mono-repository.

If you would like to see this change incorporated into `conventional-changelog` please consider re-opening the issue against the `conventional-changelog` mono-repository.
