### ISSUE TITLE
Document Commit Hash Type Check 

### ISSUE THREAD

**Issue by ghost** [stevemao/conventional-changelog-angular#6]
I'm in the process of extending conventional-changelog-angular in the form of a fork, but couldn't figure out why `typeof commit.hash === 'string'` was necessary. In what cases would the hash not be a string?

If it's needed could a unit test be added to help get the project up to 100% test coverage.

**Comment by stevemao** [comment]
It's not necessary... But when I developing the tool it was buggy and sometimes the `type` is not `string`. It also assumes that from upstream, `commit.hash` could be anything.

**Comment by hutson** [comment]
We're closing this issue out as this repository has been merged into our [`conventional-changelog`](https://github.com/conventional-changelog/conventional-changelog) mono-repository.

If you would like to see this change incorporated into `conventional-changelog` please consider re-opening the issue against the `conventional-changelog` mono-repository.
