### ISSUE TITLE
Use Map for Commit Type Conversions

### ISSUE THREAD

**Issue by ghost** [stevemao/conventional-changelog-angular#7]
There are numerous conditionals in the `writerOpts` `transform` function to map the origin commit type to a new name. 

``` javascript
var typeMappings = {
  feat: 'Features'
}

commit.type = typeMappings[commit.type] || commit.type;
```

It would help keep cyclomatic complexity down. (jshint is warning on that long list of `if` statements)

**Comment by stevemao** [comment]
Do you just want to refactor the code? I don't really care if you want to do it.

**Comment by hutson** [comment]
We're closing this issue out as this repository has been merged into our [`conventional-changelog`](https://github.com/conventional-changelog/conventional-changelog) mono-repository.

If you would like to see this change incorporated into `conventional-changelog` please consider re-opening the issue against the `conventional-changelog` mono-repository.
